### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by timnash2011** [bupticybee/TexasHoldemSolverJava#11]
![image](https://user-images.githubusercontent.com/37571621/113731853-af938280-972b-11eb-8d88-52297582469a.png)

**Comment by timnash2011** [comment]
I got this error when use the GUI even I used a small range and default configs.

**Comment by bupticybee** [comment]
This is a known issue. You must have installed java32 instead of java64. Or the env variables are messed. Try install 64bit java and run again.

**Comment by bupticybee** [comment]
Closing because this issue is inactive for 3 weeks, reopen if necessary.

**Comment by haosome6** [comment]
>  Try install 64bit java and run again.

It seems like 64bit is referred to x64 instead of x86. But in the README file, it said we need to install x86 version. I'm a little confused. Moreover, the link in README file to download x86 Java Runtime Environment doesn't even have x86 version for macOS.

**Comment by bupticybee** [comment]
> > Try install 64bit java and run again.
> 
> It seems like 64bit is referred to x64 instead of x86. But in the README file, it said we need to install x86 version. I'm a little confused. Moreover, the link in README file to download x86 Java Runtime Environment doesn't even have x86 version for macOS.

That's a typo, my mistake.

Thanks for the tips and sorry for your inconvenience~
