### ISSUE TITLE
How to run solver?

### ISSUE THREAD

**Issue by benbae300** [bupticybee/TexasHoldemSolverJava#12]
Hey, there seems to be a lot of newer files uploaded than it was in the tutorial video/README, would it be possible to get an update on how to run the newer files? Thanks so much! For example, java_interface.py is no longer available.

**Comment by benbae300** [comment]
sorry, clearly i cant read directions : D

**Comment by bupticybee** [comment]
So this problem is solved? Let me know if there are any other problems.
