### ISSUE TITLE
压缩包解压后直接运行jar，点击按钮报错

### ISSUE THREAD

**Issue by Winne599** [bupticybee/TexasHoldemSolverJava#13]
按照哔哩哔哩视频中解压了zip，但是直接运行jar点击按钮报错了，我的电脑是Mac，jdk是8，这个和jdk版本有关系吗，但是我在idea中启动项目（依旧是jdk8）点击按钮都没问题

**Comment by Winne599** [comment]
<img width="225" alt="构建树log" src="https://user-images.githubusercontent.com/39027685/115006716-c7ad9380-9edb-11eb-85cc-89a06d45ae3c.png">
<img width="653" alt="开始计算log" src="https://user-images.githubusercontent.com/39027685/115006765-d2682880-9edb-11eb-8fd9-75542e0169a8.png">
<img width="719" alt="启动后的log" src="https://user-images.githubusercontent.com/39027685/115006772-d4ca8280-9edb-11eb-9949-322b42f00266.png">
<img width="352" alt="选择桌面底牌log" src="https://user-images.githubusercontent.com/39027685/115006777-d5631900-9edb-11eb-8391-3bdc7d83ffb6.png">
<img width="709" alt="选择OOP范围log" src="https://user-images.githubusercontent.com/39027685/115006784-d5fbaf80-9edb-11eb-9091-4e66a19e3ef3.png">

**Comment by bupticybee** [comment]
你的问题和 https://github.com/bupticybee/TexasHoldemSolverJava/issues/9 比较类似，一般这种问题可能由两种问题引起：
1. java版本问题，java需要是64位java，这和是不是java8没关系
2. 安装路径中不能有中文

你可以先尝试这两种方法

**Comment by bupticybee** [comment]
你的问题和 https://github.com/bupticybee/TexasHoldemSolverJava/issues/9 比较类似，一般这种问题可能由两种问题引起：
1. java版本问题，java需要是64位java，这和是不是java8没关系
2. 安装路径中不能有中文

你可以先尝试这两种方法

**Comment by Winne599** [comment]
![image](https://user-images.githubusercontent.com/39027685/115114981-92c93b80-9fc4-11eb-9bc4-0666b23942f9.png)
嗯……感觉自己这两条好像没问题

**Comment by bupticybee** [comment]
那可以尝试在命令行启动solver 尝试使用命令：
java -jar riversolver. jar

**Comment by Winne599** [comment]
> 那可以尝试在命令行启动solver 尝试使用命令：
> java -jar riversolver. jar

已解决，感谢作者耐心回复，总结一下：可到jar包目录下用“java -jar jar包名称“方式来启用jar包，但是jar包一定要和解压后的resources文件在一个文件夹下，否则启动还是和直接双击一样报错；
以及求问作者和大家，双击jar和用命令行启动有什么区别，为什么双击jar不可行？用命令行启动为什么还要依赖resources文件？

**Comment by bupticybee** [comment]
> > 那可以尝试在命令行启动solver 尝试使用命令：
> > java -jar riversolver. jar
> 
> 已解决，感谢作者耐心回复，总结一下：可到jar包目录下用“java -jar jar包名称“方式来启用jar包，但是jar包一定要和解压后的resources文件在一个文件夹下，否则启动还是和直接双击一样报错；
> 以及求问作者和大家，双击jar和用命令行启动有什么区别，为什么双击jar不可行？用命令行启动为什么还要依赖resources文件？

1. 这个错误原因是java 64位安装好了，但是环境变量没有配置好，双击的时候调用的还是32位java
2. resource文件夹下放置了许多solver需要的资源文件，就像你玩windows游戏的时候除了主程序还有很多辅助文件一样

**Comment by bupticybee** [comment]
由于问题已经解决，关闭issue
