### ISSUE TITLE
`output_strategy.json` not generated?

### ISSUE THREAD

**Issue by battermann** [bupticybee/TexasHoldemSolverJava#14]
Hey,
first, this is an awesome program!
Maybe this is more a question than an issue, in the description it says the `output_strategy.json` is generated after solving, but it is either not or I don't know where it is located.
I am using macOS, and I am happy to provide all the information you need.
Thanks

**Comment by bupticybee** [comment]
oh you have to modify the output directory in the script first

**Comment by bupticybee** [comment]
by default it's generated in "resources/outputs/outputs_strategy.json"

**Comment by battermann** [comment]
That works if I start the program from the command line.
However, when I start the GUI no `outputs_strategy.json` file is generated.
There is one in `resources/outputs/` but that contains the result of the default configuration and doesn't change when I run a new solve.

**Comment by bupticybee** [comment]
> That works if I start the program from the command line.
> However, when I start the GUI no `outputs_strategy.json` file is generated.
> There is one in `resources/outputs/` but that contains the result of the default configuration and doesn't change when I run a new solve.

that's right.  gui version don't support dump strategy to disk

**Comment by battermann** [comment]
Got it. Thanks!

**Comment by bupticybee** [comment]
Closing because the problem is solved.
