### ISSUE TITLE
Exception in thread "Thread-0" java.lang.RuntimeException: load config failed: cannot find config file

### ISSUE THREAD

**Issue by yuwenyang0617** [bupticybee/TexasHoldemSolverJava#17]
initizing...
loading holdem compairer dictionary...
Exception in thread "Thread-0" java.lang.RuntimeException: load config failed: cannot find config file
	at icybee.solver.gui.SolverGui.loadConfig(SolverGui.java:100)
	at icybee.solver.gui.SolverGui.load_compairer(SolverGui.java:106)
	at icybee.solver.gui.SolverGui.initize(SolverGui.java:229)
	at icybee.solver.gui.SolverGui.access$000(SolverGui.java:23)
	at icybee.solver.gui.SolverGui$1.run(SolverGui.java:303)

**Comment by bupticybee** [comment]
This error is most likely due to wrog working directory. To solve you can try:
- put everything in a pure english directory
- start the program from the command line using ```java -jar xxx.jar```

**Comment by yuwenyang0617** [comment]
> This error is most likely due to wrog working directory. To solve you can try:
> 
> * put everything in a pure english directory
> * start the program from the command line using `java -jar xxx.jar`

操作系统是macOS，两种方式都是尝试了，可是还是找不到配置文件

**Comment by bupticybee** [comment]
麻烦截屏你的应用路径发在这里，我帮你排查下

**Comment by yuwenyang0617** [comment]
> 麻烦截屏你的应用路径发在这里，我帮你排查下

路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
截图：
![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)

刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException  at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)

想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？

**Comment by bupticybee** [comment]
> > 麻烦截屏你的应用路径发在这里，我帮你排查下
> 
> 路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
> 截图：
> ![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)
> 
> 刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)
> 
> 想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？

路径看似没问题，只有这一个报错？
顺便你在命令行里敲一下 java --version 确定一下java版本

**Comment by yuwenyang0617** [comment]
> > > 麻烦截屏你的应用路径发在这里，我帮你排查下
> > 
> > 
> > 路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
> > 截图：
> > ![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)
> > 刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)
> > 想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？
> 
> 路径看似没问题，只有这一个报错？
> 顺便你在命令行里敲一下 java --version 确定一下java版本

版本应该是11.0.1
![image](https://user-images.githubusercontent.com/40312147/121641406-bb038100-cac1-11eb-9a63-aa5b86287950.png)

**Comment by bupticybee** [comment]
> > > > 麻烦截屏你的应用路径发在这里，我帮你排查下
> > > 
> > > 
> > > 路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
> > > 截图：
> > > ![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)
> > > 刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)
> > > 想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？
> > 
> > 
> > 路径看似没问题，只有这一个报错？
> > 顺便你在命令行里敲一下 java --version 确定一下java版本
> 
> 版本应该是11.0.1
> ![image](https://user-images.githubusercontent.com/40312147/121641406-bb038100-cac1-11eb-9a63-aa5b86287950.png)

Hmm非常奇怪，不应该出现这种情况你的java版本应该是没有问题的。
一般都是因为路径名中带有中文出现的问题，也许是“桌面”本身是个中文名，你可以在把project移动到home目录下再尝试一下

ps:你暴露了公司名（didi）哈哈

**Comment by yuwenyang0617** [comment]
> > > > > 麻烦截屏你的应用路径发在这里，我帮你排查下
> > > > 
> > > > 
> > > > 路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
> > > > 截图：
> > > > ![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)
> > > > 刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)
> > > > 想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？
> > > 
> > > 
> > > 路径看似没问题，只有这一个报错？
> > > 顺便你在命令行里敲一下 java --version 确定一下java版本
> > 
> > 
> > 版本应该是11.0.1
> > ![image](https://user-images.githubusercontent.com/40312147/121641406-bb038100-cac1-11eb-9a63-aa5b86287950.png)
> 
> Hmm非常奇怪，不应该出现这种情况你的java版本应该是没有问题的。
> 一般都是因为路径名中带有中文出现的问题，也许是“桌面”本身是个中文名，你可以在把project移动到home目录下再尝试一下
> 
> ps:你暴露了公司名（didi）哈哈

哈哈哈~
确实非常奇怪，回家用自己的winPC就可以正常使用了，我再尝试下吧，非常感谢你的帮助~ GL

**Comment by yuwenyang0617** [comment]
> > > > > > 麻烦截屏你的应用路径发在这里，我帮你排查下
> > > > > 
> > > > > 
> > > > > 路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
> > > > > 截图：
> > > > > ![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)
> > > > > 刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)
> > > > > 想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？
> > > > 
> > > > 
> > > > 路径看似没问题，只有这一个报错？
> > > > 顺便你在命令行里敲一下 java --version 确定一下java版本
> > > 
> > > 
> > > 版本应该是11.0.1
> > > ![image](https://user-images.githubusercontent.com/40312147/121641406-bb038100-cac1-11eb-9a63-aa5b86287950.png)
> > 
> > 
> > Hmm非常奇怪，不应该出现这种情况你的java版本应该是没有问题的。
> > 一般都是因为路径名中带有中文出现的问题，也许是“桌面”本身是个中文名，你可以在把project移动到home目录下再尝试一下
> > ps:你暴露了公司名（didi）哈哈
> 
> 哈哈哈~
> 确实非常奇怪，回家用自己的winPC就可以正常使用了，我再尝试下吧，非常感谢你的帮助~ GL

放到了home目录下可以了~谢谢你~

**Comment by yuwenyang0617** [comment]
> > > > > > > > 麻烦截屏你的应用路径发在这里，我帮你排查下
> > > > > > > 
> > > > > > > 
> > > > > > > 路径：/Users/ywy/Desktop/RiverSolver/RiverSolver.jar
> > > > > > > 截图：
> > > > > > > ![image](https://user-images.githubusercontent.com/40312147/121466171-8d4b0900-c9e9-11eb-9ea6-764ee743b4f1.png)
> > > > > > > 刚才用了bash尝试操作，报错空指针，报错信息：Exception in thread "main" java.lang.NullPointerException at icybee.solver.runtime.CommandlineSolver.main(CommandlineSolver.java:108)
> > > > > > > 想问一下电脑是公司配置的，会不会与某些预装软件有关，会被拦截？
> > > > > > 
> > > > > > 
> > > > > > 路径看似没问题，只有这一个报错？
> > > > > > 顺便你在命令行里敲一下 java --version 确定一下java版本
> > > > > 
> > > > > 
> > > > > 版本应该是11.0.1
> > > > > ![image](https://user-images.githubusercontent.com/40312147/121641406-bb038100-cac1-11eb-9a63-aa5b86287950.png)
> > > > 
> > > > 
> > > > Hmm非常奇怪，不应该出现这种情况你的java版本应该是没有问题的。
> > > > 一般都是因为路径名中带有中文出现的问题，也许是“桌面”本身是个中文名，你可以在把project移动到home目录下再尝试一下
> > > > ps:你暴露了公司名（didi）哈哈
> > > 
> > > 
> > > 哈哈哈~
> > > 确实非常奇怪，回家用自己的winPC就可以正常使用了，我再尝试下吧，非常感谢你的帮助~ GL
> > 
> > 
> > 放到了home目录下可以了~ 谢谢你~
> 
> 嗯嗯果然如此，我马上要出c++版本了，比java快非常多，到时候可以多关注撒

非常支持~ 顺便膜拜大佬！

**Comment by bupticybee** [comment]
Problem solved, closing issue
