### ISSUE TITLE
Raise "java.lang.RuntimeException: java.lang.RuntimeException" when build game tree

### ISSUE THREAD

**Issue by guoxu342** [bupticybee/TexasHoldemSolverJava#18]
系统: windows 10
java version: 11.0.10
code as following:

`
from jpype import *
import yaml
import numpy as np
import sys
import os
resdir = "D:/poker/RiverSolver/RiverSolver/resources"
sys.path.append(resdir)
from python.TreeBuilder import *
import unittest
import pdb

cdir = "D:/poker/RiverSolver/RiverSolver"
path = cdir + "/RiverSolver.jar"
res = startJVM(getDefaultJVMPath(), "-ea", "-Djava.class.path=%s" % path)
os.chdir(cdir)

PokerSolver = JClass('icybee.solver.runtime.PokerSolver')

def test():
    with open('./resources/yamls/general_rule.yaml') as fhdl:
        conf = yaml.load(fhdl)
    ps_holdem = PokerSolver("Dic5Compairer",
                            "./resources/compairer/card5_dic_sorted.txt",
                            2598961,
                            ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'],
                            ['h', 's', 'd', 'c']
                            )
    rule = RulesBuilder(
            conf,
            current_commit = [2,2],
            current_round = 4,
            raise_limit = 1,
            check_limit = 2,
            small_blind = 0.5,
            big_blind = 1,
            stack = 10,
            bet_sizes = ["0.5_pot","1_pot","2_pot","all-in"],
        )
    gameTree = PartGameTreeBuilder(rule)
    depth = np.inf
    json = gameTree.gen_km_json("./tree.km".format(depth), limit=depth, ret_json=True)

    print("to build game tree in test holdem river")
    ps_holdem.build_game_tree("./tree.km")
if __name__ == '__main__':
    test()
`

报错信息如下：
D:\Mogu\venv\Scripts\python.exe D:/poker/RiverSolver/RiverSolver/resources/python/java_interface.py
D:/poker/RiverSolver/RiverSolver/resources/python/java_interface.py:297: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf = yaml.load(fhdl)
Dic5Comapirer Load  99% �� 
to build game tree in test holdem river
Traceback (most recent call last):
  File "PokerSolver.java", line 46, in icybee.solver.runtime.PokerSolver.build_game_tree
  File "SolverEnvironment.java", line 77, in icybee.solver.SolverEnvironment.gameTreeFromJson
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/poker/RiverSolver/RiverSolver/resources/python/java_interface.py", line 326, in <module>
    test()
  File "D:/poker/RiverSolver/RiverSolver/resources/python/java_interface.py", line 320, in test
    ps_holdem.build_game_tree("./tree.km")
java.lang.RuntimeException: java.lang.RuntimeException

**Comment by bupticybee** [comment]
看起来问题是建出来的树文件不是json结构，你可以尝试先使用工程中提供的json文件试试看可不可以

**Comment by bupticybee** [comment]
问题过久不活跃，暂时关闭
