### ISSUE TITLE
How to deal with multiple players?

### ISSUE THREAD

**Issue by Walter0807** [bupticybee/TexasHoldemSolverJava#19]
Thanks for sharing the great work! 

I wonder if current solvers can be applied to multiple people (e.g. 3-way pot), or are there any techniques related to it?

**Comment by bupticybee** [comment]
There are other techs for this. Multiplayer texas is too massive for pure cfr methods to handle. In Pluribus papers they use a depth-limit variant to attack the problem.

**Comment by bupticybee** [comment]
Not active too long, closing, reopen if necessary
