### ISSUE TITLE
Terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by keithandmouyue** [bupticybee/TexasHoldemSolverJava#20]
偶尔在点击范围选择按钮时候会闪退（重试依然闪退），错误报告在下面。
点结果按钮也一样，似乎和打开新窗口有关。

Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000000103333008
Exception Note:        EXC_CORPSE_NOTIFY
VM Regions Near 0x103333008:
    __LINKEDIT                  10332b000-103333000    [   32K] r--/rwx SM=COW  /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/lib/libjimage.dylib
--> VM_ALLOCATE                 103333000-103334000    [    4K] ---/rwx SM=NUL  
    VM_ALLOCATE                 103334000-103335000    [    4K] r--/rwx SM=PRV  

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x10e6513b8'
abort() called
terminating with uncaught exception of type NSException

**Comment by bupticybee** [comment]
这个问题我在mac上遇到过，不过没有debug，我是通过重启机器解决的，这个错误我无法debug，甚至连断点都打不到，所以只好暂且搁置
也就是说这个bug在mac上无法修的

**Comment by keithandmouyue** [comment]
好的，感谢。

**Comment by wulaizi** [comment]
我也遇到同样的问题了 不知道怎么解决

**Comment by bupticybee** [comment]
> 我也遇到同样的问题了 不知道怎么解决

这个问题我无法定位，所以我也不知道怎么解决，每次遇到我都是直接重启机器，问题自然消失
