### ISSUE TITLE
下载后安装问题

### ISSUE THREAD

**Issue by sd27114314** [bupticybee/TexasHoldemSolverJava#7]
![捕获1](https://user-images.githubusercontent.com/80777065/111347784-7fbc0680-86ba-11eb-95ce-32c48bfd45b3.PNG)
![捕获2](https://user-images.githubusercontent.com/80777065/111347796-82b6f700-86ba-11eb-9bee-b2b7f2674fe5.PNG)
![捕获3](https://user-images.githubusercontent.com/80777065/111347802-83e82400-86ba-11eb-99f5-37c00d3b2528.PNG)

首先声明没有编程常识，电脑是win10。按照简介，下载对应的java.exe并安装了。win+R cmd 输入java，应该算安装成功了（图1）。
然后运行了RiverSolver.jar，发现打不开手牌范围的图，只是旁边出了几排提示文字（看不懂）。以及board牌面打开设置时只显示到8（很可惜没有留下截图）。

我以为是java配置什么问题，又搜了相关文章，什么建立jdk文件夹，搞了环境变量等等。
最后发现软件也打不开了，然后删了重装java等等，再把环境变量改回来（也不知道是否改回原来的样子了）。
目前的状况如图2和图3吧，打开时选择安装目录下的javaw.exe也是没有反应。

**Comment by bupticybee** [comment]
首先，在命令行中输入java --version,将结果贴到issue中，其次运行solver只需要64位JRE，不需要JDK，最后，希望有报错截图，这样比较方便我排查

**Comment by bupticybee** [comment]
你的jar文件没有在操作系统中直接被识别出来，很大概率是JRE没有安装好

**Comment by sd27114314** [comment]
C:\Users\eric_>java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by bupticybee** [comment]
按照如下顺序排查：
1. 确定放置solver的路径中没有中文字符（比如放置在c盘/d盘根目录），再尝试双击RiverSolver.jar  打开
2. 在solver目录的地址栏中输入cmd，回车，键入命令java -jar RiverSolver.jar 观察报错，如有报错，可以将报错贴出来～

**Comment by sd27114314** [comment]
好像可以了
![捕获1](https://user-images.githubusercontent.com/80777065/111448944-e2a8ae80-8749-11eb-8da5-345815280d54.PNG)
![捕获2](https://user-images.githubusercontent.com/80777065/111448954-e5a39f00-8749-11eb-882d-4956e396c34a.PNG)

**Comment by bupticybee** [comment]
> 好像可以了
> ![捕获1](https://user-images.githubusercontent.com/80777065/111448944-e2a8ae80-8749-11eb-8da5-345815280d54.PNG)
> ![捕获2](https://user-images.githubusercontent.com/80777065/111448954-e5a39f00-8749-11eb-882d-4956e396c34a.PNG)

可以描述下解决方法？

**Comment by sd27114314** [comment]
严格按照你说的两条做的，就是双击不能打开，还是要cmd输入命令才能打开

**Comment by bupticybee** [comment]
> 严格按照你说的两条做的，就是双击不能打开，还是要cmd输入命令才能打开

Ok
