### ISSUE TITLE
翻牌跑了几个小时都没跑出来

### ISSUE THREAD

**Issue by diesfd** [bupticybee/TexasHoldemSolverJava#8]
河牌和转牌都挺正常的

**Comment by bupticybee** [comment]
翻牌现在的优化非常有问题，后续会考虑用多种方法加速，你可以先尝试勾选界面上的“use monte coral” 并且调大迭代轮数和log间隔（x50）

![image](https://user-images.githubusercontent.com/9393610/111580716-f78d4c80-87f2-11eb-805f-d98c83d2d584.png)

**Comment by bupticybee** [comment]
暂时关闭issue
